export const Types = {
    mutations: {
      ARTICLES_REQUESTED: 'ARTICLES_REQUESTED',
      ARTICLES_SUCCEEDED: 'ARTICLES_SUCCEEDED',
      ARTICLES_FAILED: 'ARTICLES_FAILED',
      ARTICLES_CANCELED: 'ARTICLES_CANCELED',
      ARTICLE_ADD_REQUESTED: 'ARTICLE_ADD_REQUESTED',
      ARTICLE_ADD_SUCCEEDED: 'ARTICLE_ADD_SUCCEEDED',
      ARTICLE_ADD_FAILED: 'ARTICLE_ADD_FAILED'
    },
    actions: {
      LOAD_ARTICLES: 'LOAD_ARTICLES',
      CANCEL_ARTICLES_REQUEST: 'CANCEL_ARTICLES_REQUEST',
      ADD_ARTICLE: 'ADD_ARTICLE'
    },
    request_status: {
      REQUESTED: 'REQUESTED',
      SUCCEEDED: 'SUCCEEDED',
      FAILED: 'FAILED',
      CANCELED: 'CANCELED'
    }
  }